# Generated by Django 3.1.6 on 2021-02-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletimes',
            name='available_time_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabletimes',
            name='available_time_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
